### ISSUE TITLE
Регистрация на форуме

### ISSUE THREAD

**Issue by spam-receiver** [MikronMIK32/framework-mik32v2-sdk#2]
Подтверждение регистрации на форуме forum.mik32.ru для активации учётной записи не приходит на электронную почту. Исправьте проблему. Не нашёл куда ещё написать об этом.

**Comment by iamcsharper** [comment]
Добрый день. Напишите свою почту

**Comment by spam-receiver** [comment]
> Добрый день. Напишите свою почту

cryptozoy@mail.ru

**Comment by iamcsharper** [comment]
Вручную активировал вас.

**Comment by spam-receiver** [comment]
> Вручную активировал вас.

Очередной геморрой на форуме:

`Вы должны включить [двухфакторную аутентификацию](https://forum.mik32.ru/index.php?account/two-step/), чтобы продолжить.`

Снова проблема с отправкой уведомлений на почту. Когда наладите нормальную работу форума?
